description: "Attention Alignemnt Experiments"

training:
  model_name: "gated_deltanet.llama_gated_deltanet"
  gradient_accumulation_steps: 1
  output_dir: "/vol/tmp2/hallepat/subq_dataset"
  # Normal heads
  # from_checkpoint: /vol/tmp2/hallepat/subq_dataset/run_20251222-2217/checkpoint-hidden-to-hidden
  from_checkpoint: null
  log_every_step: 10
  wandb_enabled: true
  wandb_project: "delta-boldt" # Insert WandB Project Name
  # splits: "0.026|0.053|0.92"
  splits: "0.0|0.0|0.33"

  stage_1:
    lr: 2e-4
    lr_scheduler: "warmup_stable_decay"
    batch_size: 20
  stage_2:
    lr: 2e-3
    lr_scheduler: "warmup_stable_decay"
    batch_size: 20
  stage_3:
    lr: 2e-4
    lr_scheduler: "cosine_with_min_lr"
    batch_size: 28
    # ce_only_stage: True
    # ce_only_share: 0.5
    # extends_seq_length: True
    # extends: [1024, 2048, 4096]
  
  optimizer: "nor_muon"
  lr_1d: 0.007

model:
  context_length: 512
  copy_teacher_params: True
  freeze: False

teacher_model:
  model_name: "HuggingFaceTB/SmolLM2-360M"
  use: True

dataset:
  output_path: /vol/tmp2/hallepat/data/fineweb-3B-gd-medium
  hugging_face_id: ["PatrickHaller/fineweb-3B"]
  # hugging_face_id: ["Salesforce/wikitext", "wikitext-2-v1"]
  split: "train"
  subset: "1.0"
  
tokenizer:
  type: "pretrained"
  pretrained_class: "llamatokenizer"
  pretrained_id: "HuggingFaceTB/SmolLM2-360M"


