description: "Attention Alignemnt Experiments"

training:
  model_name: "linear_attn.llama_linear_attn"
  gradient_accumulation_steps: 1
  output_dir: "/vol/tmp/hallepat/subq_dataset"
  from_checkpoint: null
  log_every_step: 10
  wandb_enabled: true
  wandb_project: "xqwen" # Insert WandB Project Name
  # splits: "0.024|0.176|0.8"
  splits: "0.2|0.8|0.0"

  stage_1:
    lr: 2e-4
    lr_scheduler: "warmup_stable_decay"
    batch_size: 8
  stage_2:
    lr: 2e-3
    lr_scheduler: "warmup_stable_decay"
    batch_size: 8
  stage_3:
    lr: 3e-4
    lr_scheduler: "linear"
    batch_size: 20
    # ce_only_stage: True
    # ce_only_share: 0.5
    # extends_seq_length: True
    # extends: [1024, 2048, 4096]

model:
  context_length: 512
  copy_teacher_params: True
  freeze: False

teacher_model:
  model_name: "HuggingFaceTB/SmolLM2-1.7B-Instruct"
  use: True

dataset:
  output_path: /vol/tmp/hallepat/data/fineweb-1B-la
  hugging_face_id: ["PatrickHaller/fineweb-1B"]
  # hugging_face_id: ["Salesforce/wikitext", "wikitext-2-v1"]
  split: "train"
  subset: "1.0"
  
tokenizer:
  type: "pretrained"
  pretrained_class: "llamatokenizer"
  pretrained_id: "HuggingFaceTB/SmolLM2-1.7B-Instruct"


